version: '3'

services:
  web:
    image: webdevops/php-apache-dev:8.1
    ports:
      - "80:80"
    volumes:
      - ./docroot:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - PHP_MEMORY_LIMIT=-1
    command: bash -c "chmod +x app/setup.sh && ./app/setup.sh"

  db:
    image: mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: mytheresa
      MYSQL_USER: mytheresa
      MYSQL_PASSWORD: mytheresaPassword