-- MySQL Script generated by MySQL Workbench
-- четвртак, 04. август 2022. 22:24:28 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mytheresa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mytheresa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mytheresa` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mytheresa` ;

-- -----------------------------------------------------
-- Table `mytheresa`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mytheresa`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(45) NOT NULL,
  `name` MEDIUMTEXT NOT NULL,
  `category` VARCHAR(255) NOT NULL,
  `price` DECIMAL NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sku_UNIQUE` (`sku` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytheresa`.`discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mytheresa`.`discount` (
  `percent` DECIMAL NOT NULL,
  `id` INT NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mytheresa`.`product`
-- -----------------------------------------------------
START TRANSACTION;
USE `mytheresa`;
INSERT INTO `mytheresa`.`product` (`id`, `sku`, `name`, `category`, `price`) VALUES (1, '000001', 'BV Lean leather ankle boots', 'boots', 89000);
INSERT INTO `mytheresa`.`product` (`id`, `sku`, `name`, `category`, `price`) VALUES (2, '000002', 'BV Lean leather ankle boots', 'boots', 99000);
INSERT INTO `mytheresa`.`product` (`id`, `sku`, `name`, `category`, `price`) VALUES (3, '000003', 'Ashlington leather ankle boots', 'boots', 71000);
INSERT INTO `mytheresa`.`product` (`id`, `sku`, `name`, `category`, `price`) VALUES (4, '000004', 'Naima embellished suede sandals', 'sandals', 79500);
INSERT INTO `mytheresa`.`product` (`id`, `sku`, `name`, `category`, `price`) VALUES (5, '000005', 'Nathane leather sneakers', 'sneakers', 59000);


INSERT INTO `mytheresa`.`discount` (`id`, `percent`, `type`, `value`) VALUES (1, '30', 'category', 'boots');
INSERT INTO `mytheresa`.`discount` (`id`, `percent`, `type`, `value`) VALUES (2, '15', 'single_product', '000003');

COMMIT;

